version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run start:dev
